owner: mplabs # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: MPLabs' Nextcloud
    url: https://nextcloud.mplabs.cloud
  # - name: felixduerrwald.de
  #   url: https://www.felixduerrwald.de
  - name: Mariana Friedrich
    url: https://www.mariana-friedri.ch
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mplabs.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: mplabs.cloud Status
  introTitle: "Uptime information for services running on mplabs.cloud."
  introMessage: This page provides an overview of the status of services running on mplabs.cloud. For ongoing incidents, check the linked incident reports.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
